build.gradle
src/main/java/com/weer/weer_backend/dto/HospitalInfoDto.java
src/main/java/com/weer/weer_backend/dto/HospitalRangeDto.java
src/main/java/com/weer/weer_backend/repository/AdmissionTypeRepository.java
src/main/java/com/weer/weer_backend/service/HospitalInfoService.java
src/main/resources/application.properties
src/main/resources/application.yml
src/test/java/com/weer/weer_backend/service/HospitalInfoServiceTest.java

> #5 
> getRangeAllHospital 구현

feat/#5 : HospitalService Impl & DB connection

---

src/main/java/com/weer/weer_backend/controller/LoginController.java
src/main/java/com/weer/weer_backend/entity/User.java
src/main/java/com/weer/weer_backend/service/LoginServiceImpl.java

refactor/#4 : Update LoginService

---

docker-compose.yml
prometheus.yml

> #8
> dashboard 추가를 위한 yml 파일 추가하였습니다.
일단 docker에 프로메테우스 및 그라파나 띄웠습니다.

chore: dashboard를 위한 yml 파일 작업 진행

---

src/main/java/com/weer/weer_backend/controller/LoginController.java
src/main/java/com/weer/weer_backend/dto/LoginForm.java
src/main/java/com/weer/weer_backend/dto/SecurityUser.java
src/main/java/com/weer/weer_backend/dto/UserDTO.java
src/main/java/com/weer/weer_backend/entity/User.java
src/main/java/com/weer/weer_backend/enums/Role.java
src/main/java/com/weer/weer_backend/repository/UserRepository.java
src/main/java/com/weer/weer_backend/service/LoginService.java
src/main/java/com/weer/weer_backend/service/LoginServiceImpl.java
src/main/java/com/weer/weer_backend/service/UserDetailsServiceImpl.java

refactor : LoginController refactor

---

src/main/java/com/weer/weer_backend/controller/LoginController.java
src/main/java/com/weer/weer_backend/entity/Reservation.java
src/main/java/com/weer/weer_backend/exception/ApiExceptionAdvice.java
src/main/java/com/weer/weer_backend/exception/CustomException.java
src/main/java/com/weer/weer_backend/exception/ErrorCode.java
src/main/java/com/weer/weer_backend/service/LoginServiceImpl.java
src/main/java/com/weer/weer_backend/service/ReservationService.java

> #40
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
이번 PR에서는 예외 처리를 위한 `ApiExceptionAdvice`와 `CustomException`을 추가했습니다. 이를 통해 프로젝트 내 발생하는 예외 상황을 일관된 형식으로 응답할 수 있습니다.
1. **`ApiExceptionAdvice` 클래스**:  
- `@ControllerAdvice`를 사용하여 전역 예외 처리를 담당합니다.
- `@ExceptionHandler(CustomException.class)`를 통해 `CustomException` 발생 시 예외 로그를 남기고, `CustomExceptionResponse` 형식으로 응답합니다.
2. **`CustomException` 클래스**:  
- 프로젝트 전반에서 발생하는 사용자 정의 예외 처리를 위한 클래스입니다.
- `ErrorCode`와 HTTP 상태를 포함하여 보다 명확한 예외 정보를 제공할 수 있습니다.
- `CustomExceptionResponse` 내부 클래스를 통해 예외 응답의 형식을 정의하였습니다.

CommonException add

---

src/main/java/com/weer/weer_backend/dto/RouteResponseDto.java
src/main/java/com/weer/weer_backend/entity/Emergency.java
src/main/java/com/weer/weer_backend/entity/Equipment.java
src/main/java/com/weer/weer_backend/entity/Hospital.java
src/main/java/com/weer/weer_backend/entity/Icu.java
src/main/java/com/weer/weer_backend/exception/ErrorCode.java
src/main/java/com/weer/weer_backend/repository/EmergencyRepository.java
src/main/java/com/weer/weer_backend/repository/HospitalRepository.java
src/main/java/com/weer/weer_backend/service/EmergencyApiService.java
src/main/java/com/weer/weer_backend/service/HospitalInfoService.java
src/main/java/com/weer/weer_backend/service/MapService.java

> #44 
> 병원마다의 정보가 null인 부분을 발견하여 이를 반환시에 반환되지 않도록 수정

#44 filtering & loc info fix

---

build.gradle
src/main/java/com/weer/weer_backend/config/SpringSecurityConfig.java
src/main/java/com/weer/weer_backend/config/WebConfig.java
src/main/java/com/weer/weer_backend/controller/LoginController.java
src/main/java/com/weer/weer_backend/dto/SecurityUser.java
src/main/java/com/weer/weer_backend/entity/User.java
src/main/java/com/weer/weer_backend/enums/Approve.java
src/main/java/com/weer/weer_backend/exception/ApiExceptionAdvice.java
src/main/java/com/weer/weer_backend/exception/ErrorCode.java
src/main/java/com/weer/weer_backend/filter/JWTFilter.java
src/main/java/com/weer/weer_backend/filter/JWTUtil.java
src/main/java/com/weer/weer_backend/filter/LoginFilter.java
src/main/java/com/weer/weer_backend/repository/UserRepository.java
src/main/java/com/weer/weer_backend/service/LoginService.java
src/main/java/com/weer/weer_backend/service/LoginServiceImpl.java
src/main/java/com/weer/weer_backend/service/UserDetailsServiceImpl.java
src/main/java/com/weer/weer_backend/service/UserServiceImpl.java

> #42 
> 세션 -> JWT 토큰 방식으로 변경 및 API 연동 확인

JWT토큰 로그인 방식 구현

---

build.gradle
src/main/java/com/weer/weer_backend/config/SpringSecurityConfig.java
src/main/java/com/weer/weer_backend/controller/EmergencyApiController.java
src/main/java/com/weer/weer_backend/controller/EquipmentApiController.java
src/main/java/com/weer/weer_backend/controller/HospitalInfoController.java
src/main/java/com/weer/weer_backend/controller/LoginController.java
src/main/java/com/weer/weer_backend/controller/OpenApiController.java
src/main/java/com/weer/weer_backend/controller/PatientController.java
src/main/java/com/weer/weer_backend/controller/ReservationController.java
src/main/java/com/weer/weer_backend/controller/UserController.java
src/main/java/com/weer/weer_backend/dto/ApiResponse.java
src/main/java/com/weer/weer_backend/exception/ErrorCode.java
src/main/resources/application.yml

> #50 
> ResponseEntity response에서 common ApiResponse로 변경

refactor : ApiResponse transfer

---

src/main/java/com/weer/weer_backend/config/SpringSecurityConfig.java
src/main/java/com/weer/weer_backend/controller/PatientController.java
src/main/java/com/weer/weer_backend/controller/UserController.java
src/main/java/com/weer/weer_backend/service/UserService.java
src/main/java/com/weer/weer_backend/service/UserServiceImpl.java

> #53 
> 사용자에게 직접적으로 받던 userId를 '@AuthenticationPrincipal`으로 받도록 수정
> approval변경으로 인한 로직 변경

#53 refactor : UserController userId 수정

---

src/main/java/com/weer/weer_backend/controller/PatientController.java
src/main/java/com/weer/weer_backend/controller/UserController.java

> #55 
> UserController Url fix

fix : UserController Url fix

---

src/main/java/com/weer/weer_backend/config/SpringSecurityConfig.java
src/main/java/com/weer/weer_backend/controller/EmergencyApiController.java
src/main/java/com/weer/weer_backend/controller/LoginController.java
src/main/java/com/weer/weer_backend/dto/SecurityUser.java
src/main/java/com/weer/weer_backend/dto/TokenDto.java
src/main/java/com/weer/weer_backend/filter/JWTFilter.java
src/main/java/com/weer/weer_backend/filter/LoginFilter.java
src/main/java/com/weer/weer_backend/filter/TokenProvider.java
src/main/java/com/weer/weer_backend/service/LoginServiceImpl.java

> #52 
> JWT Filter,  Login Filter Refactoring, Add TokenDTO, TokenProvider

JWT Token Refactoring

---

src/main/java/com/weer/weer_backend/config/SpringSecurityConfig.java

> #58
> conflict error fix : LoginFilter

fix : conflict error fix

---

src/main/java/com/weer/weer_backend/controller/PatientController.java

> #60 
> createPatientCondition fix

fix : createPatientCondition fix

---

src/main/java/com/weer/weer_backend/config/SpringSecurityConfig.java
src/main/java/com/weer/weer_backend/controller/HospitalInfoController.java
src/main/java/com/weer/weer_backend/repository/HospitalRepository.java
src/main/java/com/weer/weer_backend/service/HospitalInfoService.java

feat : distance hospitalInfo Impl

---

src/main/java/com/weer/weer_backend/controller/HospitalInfoController.java
src/main/java/com/weer/weer_backend/dto/HospitalDistanceDto.java
src/main/java/com/weer/weer_backend/service/HospitalInfoService.java
src/test/java/com/weer/weer_backend/service/HospitalInfoServiceTest.java

> #68
> 병원 필터링, 거리순 정보에도 소요시간, 이동거리 추가

feat : hospital Info distance add

---

src/main/java/com/weer/weer_backend/controller/LoginController.java
src/main/java/com/weer/weer_backend/exception/ErrorCode.java
src/main/java/com/weer/weer_backend/service/LoginServiceImpl.java

feat: Add duplicate check to signup service

---

src/main/java/com/weer/weer_backend/entity/Equipment.java

fix: 장비 HVHYPOAYN 필드명 오타 수정

---

src/main/java/com/weer/weer_backend/controller/ReservationController.java

> #83 
> 병원측에서 환자로부터 요청된 예약을 승인/반려 하는 것을 결정하는 기능을 API와 성공적으로 연동

feat: Hospital's Approve/Decline Impl

---

.gitignore
Dockerfile
src/main/java/com/weer/weer_backend/config/WebConfig.java
src/main/java/com/weer/weer_backend/entity/Emergency.java
src/main/java/com/weer/weer_backend/entity/Equipment.java
src/main/java/com/weer/weer_backend/entity/Hospital.java
src/main/java/com/weer/weer_backend/entity/Icu.java
src/main/resources/application.yml

> #85 
> docker build script add

feat : docker build

---

build.gradle
src/main/java/com/weer/weer_backend/config/SpringSecurityConfig.java
src/main/java/com/weer/weer_backend/dto/ERAnnouncementDTO.java
src/main/java/com/weer/weer_backend/entity/ERAnnouncement.java
src/main/java/com/weer/weer_backend/service/CommonApiService.java
src/main/java/com/weer/weer_backend/service/ERAnnouncementService.java
src/main/java/com/weer/weer_backend/service/EmergencyApiService.java
src/main/java/com/weer/weer_backend/service/EquipmentApiService.java
src/main/resources/application.yml

> #87 
> ERAnnouncement refactor & actuator add

feat : ERAnnouncement refactor & actuator add

---

src/main/java/com/weer/weer_backend/entity/ERAnnouncement.java
src/main/java/com/weer/weer_backend/entity/Emergency.java
src/main/java/com/weer/weer_backend/service/CommonApiService.java
src/main/java/com/weer/weer_backend/service/ERAnnouncementService.java
src/main/java/com/weer/weer_backend/service/EmergencyApiService.java
src/main/java/com/weer/weer_backend/service/EquipmentApiService.java
src/main/java/com/weer/weer_backend/service/HospitalApiService.java
src/main/java/com/weer/weer_backend/service/IcuApiService.java
src/main/java/com/weer/weer_backend/util/XmlParsingUtils.java

fix: xml 파싱 및 저장 로직 수정

---

jenkinsfile
src/main/java/com/weer/weer_backend/controller/LoginController.java
src/main/resources/application.yml

> ex) #91
> 젠킨스를 활용해 ECR에 이미지를 업로드 하는 것까지 진행하였습니다.

Feature/91 : jenkinsfile 업로드 

---

src/main/java/com/weer/weer_backend/controller/ReservationController.java
src/main/java/com/weer/weer_backend/repository/UserRepository.java
src/main/java/com/weer/weer_backend/service/UserService.java
src/main/java/com/weer/weer_backend/service/UserServiceImpl.java

> #93 
> 로그인한 계정에 해당하는 병원으로 들어온 요청을 확인하게끔 구현. (기존에는 Hospital_id값을 fix 해놓음)

feat/93 : 병원측 예약요청페이지 기능 추가 및 수정

---

build.gradle
src/main/resources/application.yml

Chore: Prometheus Actuator 엔드포인트 활성화

---

build.gradle
src/main/java/com/weer/weer_backend/config/LoggingAspect.java
src/main/java/com/weer/weer_backend/config/SpringSecurityConfig.java
src/main/java/com/weer/weer_backend/config/SwaggerConfig.java
src/main/java/com/weer/weer_backend/config/WebConfig.java
src/main/java/com/weer/weer_backend/dto/EmergencyDTO.java
src/main/java/com/weer/weer_backend/dto/HospitalRangeDto.java
src/main/java/com/weer/weer_backend/dto/RouteResponseDto.java
src/main/java/com/weer/weer_backend/filter/JWTFilter.java
src/main/java/com/weer/weer_backend/service/HospitalInfoService.java
src/main/resources/application.yml
src/main/resources/logback-spring.xml

#98
- AOP 로깅 기능 추가
- AOP를 활용하여 특정 메서드 호출 시 자동으로 로그를 기록하도록 로직 추가
- 사용자 식별 정보 (userIdx), 추적 ID (traceId) 등 주요 필드를 로깅하여 디버깅과 모니터링을 쉽게 할 수 있도록 함
- 로컬, 개발, 스테이징, 라이브 환경별로 다른 로깅 방식 적용 (콘솔 로그 vs JSON 로그)
Around 어노테이션을 이용한 로깅 AOP 적용
로깅 시 Request URL, HTTP Method, 실행시간 등을 포함한 로그 추가
```java
@Around("controllerPointcut()")
public Object logControllerRequests(ProceedingJoinPoint joinPoint) throws Throwable {
String methodName = joinPoint.getSignature().getName();
String className = joinPoint.getTarget().getClass().getSimpleName();
logger.info("Request URL: {}", httpServletRequest.getRequestURL());
logger.info("HTTP Method: {}", httpServletRequest.getMethod());
logger.info("Request Params: {}", httpServletRequest.getQueryString());
logger.info("Executing {}.{}() with arguments: {}", className, …
```

AOP Logging add

---

build.gradle
jenkinsfile

> #91 
> Sonarqube와 argoCD를 위한 gitops repo 커밋 및 푸시를 하는 script 추가

feat: Impl SonarQube & GitOps Repo commit and push

---

src/main/java/com/weer/weer_backend/entity/BaseEntity.java

refactor: Update BaseEntity about modified_at

---

src/main/java/com/weer/weer_backend/controller/PatientController.java

> 웹에서 이송완료 환자 리스트 최신순으로 정렬하기 위해 수정
> patientController : user/reservation API
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

feat: Update PatientController.java

---

jenkinsfile

> #108 
> deployment를 rollout으로 변경

refactor: Update Jenkinsfile for blue-green CD

---

docker-compose.yml
src/main/java/com/weer/weer_backend/config/LoggingAspect.java
src/main/java/com/weer/weer_backend/config/SwaggerConfig.java
src/main/java/com/weer/weer_backend/controller/LoginController.java
src/main/java/com/weer/weer_backend/controller/PatientController.java
src/main/java/com/weer/weer_backend/dto/ApiResponse.java
src/main/java/com/weer/weer_backend/dto/ERAnnouncementDTO.java
src/main/java/com/weer/weer_backend/dto/HospitalDTO.java
src/main/java/com/weer/weer_backend/dto/HospitalDistanceDto.java
src/main/java/com/weer/weer_backend/dto/PatientConditionDTO.java
src/main/java/com/weer/weer_backend/dto/PatientConditionResponseDTO.java
src/main/java/com/weer/weer_backend/dto/ReservationDTO.java
src/main/java/com/weer/weer_backend/dto/ReservationRequestDto.java
src/main/java/com/weer/weer_backend/dto/SecurityUser.java
src/main/java/com/weer/weer_backend/dto/UserDTO.java
src/main/java/com/weer/weer_backend/repository/PatientConditionRepository.java
src/main/java/com/weer/weer_backend/service/HospitalInfoService.java
src/main/java/com/weer/weer_backend/service/PatientService.java
src/main/resources/logback-spring.xml
src/test/java/com/weer/weer_backend/service/PatientServiceTest.java

> #112 
- `ApiResponse.java`에서 공통 응답 구조 개선 및 불필요한 코드 제거
- `ERAnnouncementDTO.java` 및 관련 DTO 파일 리팩토링: 중복된 필드를 제거하고 재사용 가능한 구조로 변경
- `PatientController.java`의 컨트롤러 로직 단순화 및 서비스 계층과의 역할 명확화
- `PatientServiceTest.java`에서 유닛 테스트 보강 및 모킹(mocking) 로직 개선
- `SwaggerConfig.java`에서 중복된 설정 제거 및 불필요한 설정 삭제

Bug Fix and Code Improvement
